- menu_name: "CONTACT AND MORE"

- name: "CONTACT!"
  url: "/contact/"
  title: "DROP A LINE!"

- name: "RSS"
  url: "/feed.xml"
  title: "SUBSCRIBE TO MY RSS FEED!"

- name: "ATOM"
  url: "/atom.xml"
  title: "SSUBSCRIBE TO MY ATOM FEED!"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "SITEMAP!"
